In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size=10000

In [4]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6618, 4796, 7006, 302],
 [6618, 4796, 7006, 7448],
 [6618, 1799, 7006, 602],
 [7559, 3939, 3024, 2390, 6712],
 [7559, 3939, 3024, 2390, 5561],
 [9434, 6618, 6015, 7006, 924],
 [4954, 4967, 7240, 2390]]

In [7]:
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6618 4796 7006  302]
 [   0    0    0    0 6618 4796 7006 7448]
 [   0    0    0    0 6618 1799 7006  602]
 [   0    0    0 7559 3939 3024 2390 6712]
 [   0    0    0 7559 3939 3024 2390 5561]
 [   0    0    0 9434 6618 6015 7006  924]
 [   0    0    0    0 4954 4967 7240 2390]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Sahil\OneDrive\my-learnings\ML\projects-deep-learning\simpleRNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step


array([[[-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [ 0.03940285, -0.03078408, -0.02039279, -0.02273327,
          0.02436615, -0.02719665, -0.04777265,  0.00620105,
         -0.03311364, -0.03268263],
        [-0.01604442,  0.00076782, -0.02808224,  0.01326715,
          0.03911669, -0.0161503 ,  0.03778186,  0.01836432,
         -0.04505125,  0.04808045],
        [-0.0205814 ,  0.03572742,  0.01330839,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6618, 4796, 7006,  302], dtype=int32)

In [16]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


array([[[-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [-0.01808927,  0.00835795, -0.04944389,  0.01872336,
         -0.00143074,  0.03621639, -0.00569401, -0.00825984,
          0.01385227, -0.03600929],
        [ 0.03940285, -0.03078408, -0.02039279, -0.02273327,
          0.02436615, -0.02719665, -0.04777265,  0.00620105,
         -0.03311364, -0.03268263],
        [-0.01604442,  0.00076782, -0.02808224,  0.01326715,
          0.03911669, -0.0161503 ,  0.03778186,  0.01836432,
         -0.04505125,  0.04808045],
        [-0.0205814 ,  0.03572742,  0.01330839,  0.0